# pipeline.yml
stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: python:3.11
  script:
    - echo "Building application..."
    - mkdir -p dist
    - echo "v1.0.0" > dist/version.txt

deploy-job:
  stage: deploy
  image: alpine:latest
  script:
    - echo "Deploying application..."
    - cat dist/version.txt
    - echo "Deployment complete!"

test-job:
  stage: test
  image: python:3.11
  script:
    - echo "Running tests..."
    - python -c "print('All tests passed!')"

